name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Encodage sans erreur de "Batman"
      id: encodage-sans-erreur-de-batman
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Encodage sans erreur de "Batman"
        setup-command: ''
        command: java -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8
          -classpath ./out/production/Checksum com.cegepst.App
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ENCODAGE-SANS-ERREUR-DE-BATMAN_RESULTS: "${{steps.encodage-sans-erreur-de-batman.outputs.result}}"
      with:
        runners: encodage-sans-erreur-de-batman
